### ISSUE TITLE
Probably falsely detected problems in default HUD files

### ISSUE THREAD

**Issue by qkeitoe** [cooolbros/vscode-vdf#12]
I'm not sure if all of the problems listed below are really false detections, but at least some seem to be.

* A lot of values for `ControlName` used in files inside `hl2_misc_dir.vpk` and `platform_misc_dir.vpk` are marked as not valid. Such as `URLLabel` (used in m0rehud) or `CReplayBrowserDetailsPanel` (used in ahud).
  ![2023-09-11_18-37-43](https://github.com/cooolbros/vscode-vdf/assets/66339491/c9897671-4edc-4a5a-b293-6db5c666bfa2)
* `"textAlignment"` `"left"`/`"Left"`, `"northwest"`, `"center-west"`. The first value is used in many files. The second one has about 10 uses. The last is only used once, so it's very likely a typo.
* `"paintborder"`, `"paintbackground"` `"2"`. Each is used only twice, so...
*
  ![image](https://github.com/cooolbros/vscode-vdf/assets/66339491/9acec6ee-962c-4871-b754-bc7573bc229d)
*
  ![image](https://github.com/cooolbros/vscode-vdf/assets/66339491/8b8a7b90-ec99-46cc-960d-79b98f483067)

**Comment by cooolbros** [comment]
If the control names from `hl2_misc_dir.vpk` and `platform_misc_dir.vpk` are valid in VGUI .res I can add them in.

The textAlignment schema only contains the north/south/east/west values so that the autocompletion doesn't suggest multiple values that achieve the same thing, even though left/right are valid VGUI values. Because the values are only used in a few files it might be ok to skip them to keep simplicity in the autocompletion. Splitting the valid values and suggested values is not something I want to do either because it could be difficult to ensure consistency.

`paintbackground` `2` is a typo that is supposed to be `paintBackgroundType` `2`.

I can't replicate the "Unexpected '{'" syntax error in example.pop. Could you upload the file with the error?

Currently the HUD animations doesn't support conditionals on events, I tested this in game and its incorrect, I can fix it.

**Comment by qkeitoe** [comment]
I'm not sure about all of the control names from `hl2_misc_dir.vpk` and `platform_misc_dir.vpk`, but at least the name `URLLabel` is valid (https://github.com/Hypnootize/m0rehud/blob/a3ff95e1880121b13a2e68fd5dc271ee6ef8ec05/resource/ui/customizations/%23customization_menu/hud_customization_frame.res#L263). And I personally don't know of any non-manual way to check the rest.

Good point. After realizing the nature of these values (left/right), the following idea came to me. Since they are valid and, as I realized, do the same thing as west/east, what do you think about just replacing "left" with "west" and "right" with "east" for the "textAlignment" when automatically formatting a file (possibly with an option to disable this behavior using an extension setting)?

I got this error in the file `scripts/population/example/example.pop` from `tf2_misc_dir.vpk` (to prepare the issue I just scanned all files in the three mentioned vpks for problems (thanks vscode for automating this process)).

**Comment by cooolbros** [comment]
I've added `URLLabel` to the list, but decided not to add the other ControlNames in case they are not actually implemented in TF2, welcome to adding more if they are proven to work but there are 265 unique ControlNames in hl2 and platform misc and I dont want to test them all

Modifying the actual text content of the file when formatting is not something I want to do (the formatter should only change whitespace), however  I've created a quick fix action for common uses of textAlignment, which you can bring up with Ctrl+.

After reviewing the example.pop file I think it's not meant to be loaded as a mission because it contains multiple occurrences of invalid syntax by using placeholder values, such as `<item definition name>`. The error shown in your screenshot is actually caused by an error earlier in the file, `TeleportWhere` missing a value. The error in the screenshot is in the wrong place because the extension parser reads the next key as the value and keeps reading until the unexpected `'{'`. It's possible that the existance of `TeleportWhere` in a popfile is enough to set the behaviour without actually having a value, but this functionality is not possible to support in the extension because the popfile parser and the extension parser work in different ways. In future I may add a strict parsing option to ensure keys and values are on the same line, to anticipate syntax errors and report the position more accurately.

Finally, I added support for conditionals in HUD animation events.

**Comment by qkeitoe** [comment]
That's great! Many thanks!
