### ISSUE TITLE
Formatting removes comments!

### ISSUE THREAD

**Issue by XcapeEst** [cooolbros/vscode-vdf#5]

**Comment by cooolbros** [comment]
Can you provide a sample code  snippet for when this happens?

**Comment by XcapeEst** [comment]
```
"Resource/UI/ChatPopup.res"
{
	"InviteNotification" // xypos doesnt work here
	{
		"fieldName"			"InviteNotification"
		"zpos"				"1"
		"wide"				"200"
		"tall"				"35"
		"visible"			"1"
		"border"				"ReplayDefaultBorder"
		"paintbackground"		"0"
		"bgcolor_override"		"255 0 0 250"
	}
```

Turns into

```
"Resource/UI/ChatPopup.res"
{
	"InviteNotification"
	{
		"fieldName"				"InviteNotification"
		"zpos"					"1"
		"wide"					"200"
		"tall"					"35"
		"visible"				"1"
		"border"				"ReplayDefaultBorder"
		"paintbackground"		"0"
		"bgcolor_override"		"255 0 0 250"
	}
```

**Comment by cooolbros** [comment]
Interesting, it doesn't seem to happen for me
![formatting_demo](https://user-images.githubusercontent.com/43595566/163694016-07c6e03a-3f8b-439c-9ca4-3f6f653ebd59.gif)

Does it still happen if you disable all other extensions?

**Comment by XcapeEst** [comment]
I have been using the "VDF: Format VDF" function, and using the right-click format worked fine.

**Comment by cooolbros** [comment]
The purpose of "VDF: Format VDF" is to format snippets of VDF embedded in files of different languages (e.g. markdown). The problem is the command is yet to be updated to use the new formatting functionality (which formats comments). I will update the command in the next release.

I would suggest setting `editor.formatOnSave` to true to make formatting more convenient, rather than using "VDF: Format VDF"
